# Nombre del pipeline que se verá en la interfaz de GitHub
name: Node.js CI Backend Workflow

# Se ejecuta cada vez que hagamos push a main
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [ main ]

jobs:
  laboratorio-ci:
    # Le decimos a GitHub que levante una máquina virtual con Ubuntu Linux limpio
    runs-on: ubuntu-latest

    # Creamos la base de datos temporal a GitHub Actions
    services:
      mysql-container:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: mensajes_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      # Descargamos el código de tu repositorio dentro de la máquina virtual
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      # Instalamos Node.js en esa máquina virtual
      - name: Configurar entorno de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ejecutamos el comando de prueba para verificar que el Linux responde
      - name: Verificar versiones en la nube
        run: |
          echo "El servidor Linux de GitHub Actions está vivo."
          node -v
          npm -v

      # Instalamos las dependencias de producción y desarrollo
      # Usamos 'npm ci' en lugar de 'npm install' porque está optimizado para entornos de CI
      - name: Instalar dependencias del Backend
        run: |
          cd backend_message
          npm ci

      # Validamos la sintaxis y calidad del código (Análisis Estático)
      - name: Ejecutar Linter (Revisión de código)
        run: |
          cd backend_message
          npm run lint --if-present

      - name: Inicializar tablas de la Base de Datos
        run: |
          docker exec -i $(docker ps -q --filter ancestor=mysql:latest) mysql -u root mensajes_db < backend_message/database/init.sql

      # Ejecutar las pruebas automatizadas
      - name: Ejecutar Pruebas Unitarias
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306 
          DB_USER: root
          DB_PASSWORD: ""
          DB_NAME: mensajes_db
          JWT_SECRET: MiClaveSecreta
        run: |
          cd backend_message
          npm test --if-present
  
  deploy:
    name: Despliegue en Render
    needs: laboratorio-ci 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Disparar Deploy en Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"